services:
  saharad:
    image: ghcr.io/saharalabsai/sahara/saharad:0.3.0-testnet-beta
    restart: unless-stopped
    user: root
    volumes:
      - ./chain-data:/sahara/.saharad
    command: ["start", "--home", "/sahara/.saharad"]
    ports:
      - 26656:26656
      - 26657:26657
      - 16161:16161
      - 16162:16162

    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "10"
